import type { CSSProperties, ReactNode } from 'react'

export type TicketType = { id: number; name: string; description?: string; kind: string; price: number; currency: string; quantity: number; sold: number }
export type EventItem = { id: number; title: string; description: string; category: string; city: string; country: string; countryCode?: string; venueName?: string; roomName?: string; addressLine?: string; postalCode?: string; state?: string; online?: boolean; onlineAccessUrl?: string; latitude?: number; longitude?: number; organizerName: string; organizerEmail?: string; startsAt: string; endsAt: string; capacity: number; brandColor: string; coverImageUrl?: string; generatedImageUrl?: string; mediaUrls?: string; videoUrl?: string; allowedPaymentMethods?: string; reservationFreeUntil?: string; reservationHoldDays?: number; tickets?: TicketType[] }
export type Account = { id: number; fullName: string; email: string; phone?: string; role: string; verified: boolean; apiToken: string }
export type Attendee = { id: number; fullName: string; email: string; phone?: string; status: string; qrCode: string; registeredAt: string; checkedInAt?: string }
export type AddressSuggestion = { label: string; addressLine: string; city: string; postalCode: string; state: string; country: string; countryCode: string; latitude: number; longitude: number }
export type OrganizerEvent = { event: EventItem; participants: Attendee[]; reservations: any[]; participantCountries: Record<string, number>; countdownSeconds: number }
export type TicketHistory = { tickets: Attendee[]; purchases: any[]; invoices: any[] }
export type Toast = { kind: 'success' | 'error' | 'info'; text: string }

export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080/api'
export const platformFee = 4.5
export const categories = ['music', 'business', 'conference', 'dating', 'humour & comedy', 'cinema', 'webinar', 'sport', 'social', 'tourism', 'formation', 'tech', 'food', 'art']
export const countries = [
  { name: 'Allemagne', iso: 'DE', dial: '+49' }, { name: 'France', iso: 'FR', dial: '+33' }, { name: 'Côte d’Ivoire', iso: 'CI', dial: '+225' }, { name: 'Cameroun', iso: 'CM', dial: '+237' }, { name: 'RDC', iso: 'CD', dial: '+243' }, { name: 'Sénégal', iso: 'SN', dial: '+221' }, { name: 'Belgique', iso: 'BE', dial: '+32' }, { name: 'Suisse', iso: 'CH', dial: '+41' }, { name: 'Canada', iso: 'CA', dial: '+1' }, { name: 'États-Unis', iso: 'US', dial: '+1' }
]
export const emptyPreview: EventItem = { id: 0, title: 'Votre futur événement', description: 'Prévisualisation en direct.', category: 'business', city: '', country: '', venueName: '', organizerName: '', startsAt: new Date(Date.now()+86400000).toISOString(), endsAt: new Date(Date.now()+90000000).toISOString(), capacity: 100, brandColor: '#ff7a1a', tickets: [{ id: 0, name: 'Standard', kind: 'PAID', price: 0, currency: 'EUR', quantity: 100, sold: 0 }] }

export async function api<T>(path: string, options?: RequestInit): Promise<T> { const headers = { 'Content-Type': 'application/json', ...(options?.headers ?? {}) }; const res = await fetch(`${API_URL}${path}`, { ...options, headers }); if (!res.ok) { const raw = await res.text(); try { const parsed = JSON.parse(raw); throw new Error(parsed.message || raw) } catch { throw new Error(raw || `${res.status} ${res.statusText}`) } } return res.json() }
export async function uploadMedia(file: File, folder = 'events'): Promise<string> { const fd = new FormData(); fd.append('file', file); fd.append('folder', folder); const res = await fetch(`${API_URL}/media/upload`, { method: 'POST', body: fd }); if (!res.ok) throw new Error(await res.text()); const data = await res.json(); return data.publicUrl }
export function go(path: string) { history.pushState(null, '', path); dispatchEvent(new PopStateEvent('popstate')); scrollTo({ top: 0, behavior: 'smooth' }) }
export function parseQuery(path: string) { return new URLSearchParams(path.split('?')[1] ?? '') }
export function date(v: string) { return new Intl.DateTimeFormat('fr-FR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(v)) }
export function money(ticket?: TicketType) { if (!ticket) return 'Prix à définir'; return ticket.price === 0 ? 'Gratuit' : `${ticket.price.toLocaleString('fr-FR')} ${ticket.currency}` }
export function addressOnly(e: EventItem) { return [e.addressLine, e.postalCode, e.city, e.country].filter(Boolean).join(', ') }
export function eventPlace(e: EventItem) { if (e.online) return '🌐 En ligne · lien envoyé par QR Code + email/WhatsApp'; const room = e.roomName ? `${e.roomName} · ` : ''; const exact = addressOnly(e); return `📍 ${room}${e.venueName ? e.venueName + ' · ' : ''}${exact || `${e.city}, ${e.country}`}` }
export function mapEmbed(e: EventItem) { const q = e.latitude && e.longitude ? `${e.latitude},${e.longitude}` : addressOnly(e); return `https://www.openstreetmap.org/export/embed.html?layer=mapnik&marker=${encodeURIComponent(q)}` }
export function phone(fd: FormData, base: string) { const dial = String(fd.get(`${base}Dial`) || ''); const raw = String(fd.get(base) || '').trim().replace(/^0+/, ''); return raw ? `${dial}${raw}` : '' }
export function eventOptions(events: EventItem[]) { return <datalist id="eventTitles">{events.map(e => <option value={e.title} key={e.id}>{e.city}, {e.country}</option>)}</datalist> }


export function Header({ account, setAccount }: { account: Account | null; setAccount: (a: Account | null) => void }) { return <nav className="nav"><button className="brand" onClick={() => go('/')}><span>✦</span>LightEvents</button><div className="links"><button onClick={() => go('/events')}>Événements</button><button onClick={() => go('/create')}>Publier</button><button onClick={() => go('/organizer')}>Organisateur</button><button onClick={() => go('/tickets')}>Mes tickets</button><button onClick={() => go('/help')}>ChatBot</button>{account?.role === 'ADMIN' && <button onClick={() => go('/admin')}>Admin</button>}</div><div className="authBox">{account ? <><small>{account.fullName} · {account.verified ? '✅' : '⚠️'}</small><button onClick={() => setAccount(null)}>Sortir</button></> : <button onClick={() => go('/auth')}>Connexion</button>}</div></nav> }
export function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="sectionTitle page"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><p>{text}</p></section> }
export function EventGrid({ events }: { events: EventItem[] }) { if (!events.length) return <section className="panel page emptyState">Aucun événement pour le moment.</section>; return <section className="eventGrid page">{events.map(e => <article className="eventCard" key={e.id} style={{ '--accent': e.brandColor || '#7c3aed' } as CSSProperties}><img src={e.coverImageUrl || e.generatedImageUrl || '/favicon.svg'} /><div className="eventBody"><span>{e.category}</span><h3>{e.title}</h3><p>{e.description}</p><small>{eventPlace(e)} · 🗓️ {date(e.startsAt)}</small><div><strong>{money(e.tickets?.[0])}</strong><button onClick={() => go(`/events/${e.id}`)}>Détails</button></div></div></article>)}</section> }
export function PhoneField({ base, label }: { base: string; label: string }) { return <div className="two"><select name={`${base}Dial`} defaultValue="+49">{countries.map(c => <option key={c.iso} value={c.dial}>{c.name} {c.dial}</option>)}</select><input name={base} placeholder={label} /></div> }
export function CountrySelect({ name }: { name: string }) { return <select name={name} defaultValue="DE">{countries.map(c => <option key={c.iso} value={c.iso}>{c.name}</option>)}</select> }
export function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modalBackdrop"><section className="modal panel"><button className="close" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div> }
export function PageHero({ title, text }: { title: string; text: string }) { return <section className="pageHero page"><span className="eyebrow">LightEvents</span><h1>{title}</h1><p>{text}</p></section> }


export function AppFooter(){ const payments=['ORANGE_MONEY','MTN_MONEY','WAVE','AIRTEL_MONEY','MOOV_MONEY','STRIPE','PAYPAL']; return <footer className="footer richFooter"><div className="paymentLogos">{payments.map(p=><span key={p}>{p.replace('_',' ')}</span>)}</div><div className="footerLinks"><button onClick={()=>go('/policy/privacy')}>Privacy Policy</button><button onClick={()=>go('/policy/terms')}>Terms</button><button onClick={()=>go('/policy/refund')}>Refund Policy</button><button onClick={()=>go('/policy/cookies')}>Cookies</button><button onClick={()=>go('/help')}>Support</button></div><p>LightEvents · frais plateforme {platformFee}% · paiements internationaux et Mobile Money.</p></footer> }
export function ScrollTopButton(){ return <button className="scrollTop" onClick={()=>scrollTo({top:0,behavior:'smooth'})}>↑</button> }
