import type { CSSProperties, ReactNode } from 'react'

export type TicketType = { id: number; name: string; description?: string; kind: string; price: number; currency: string; quantity: number; sold: number }
export type EventItem = { id: number; title: string; description: string; category: string; categories?: string; city: string; country: string; countryCode?: string; venueName?: string; roomName?: string; addressLine?: string; postalCode?: string; state?: string; online?: boolean; onlineAccessUrl?: string; latitude?: number; longitude?: number; organizerName: string; organizerEmail?: string; startsAt: string; endsAt: string; capacity: number; brandColor: string; coverImageUrl?: string; generatedImageUrl?: string; mediaUrls?: string; videoUrl?: string; allowedPaymentMethods?: string; reservationFreeUntil?: string; reservationHoldDays?: number; payoutMethod?: string; payoutAccountRef?: string; payoutSchedule?: string; tickets?: TicketType[] }
export type Account = { id: number; fullName: string; email: string; phone?: string; role: string; verified: boolean; apiToken: string; codePreview?: string; message?: string }
export type Attendee = { id: number; fullName: string; email: string; phone?: string; status: string; qrCode: string; registeredAt: string; checkedInAt?: string }
export type AddressSuggestion = { label: string; addressLine: string; city: string; postalCode: string; state: string; country: string; countryCode: string; latitude: number; longitude: number }
export type OrganizerEvent = { event: EventItem; participants: Attendee[]; reservations: any[]; participantCountries: Record<string, number>; countdownSeconds: number }
export type TicketHistory = { tickets: Attendee[]; purchases: any[]; invoices: any[] }
export type Toast = { kind: 'success' | 'error' | 'info'; text: string }
export type ModuleField = { name: string; label: string; type?: string; placeholder?: string; options?: string[]; required?: boolean }
export type PlatformModule = { key: string; area: 'organizer' | 'admin' | 'developer'; title: string; shortTitle: string; endpoint: string; method: 'GET' | 'POST' | 'PATCH' | 'DELETE'; description: string; fields: ModuleField[] }

export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8080/api'
export const platformFee = 4.5
export const categories = ['music', 'business', 'conference', 'dating', 'humour & comedy', 'cinema', 'webinar', 'sport', 'social', 'tourism', 'formation', 'tech', 'food', 'art']
export const countries = [
  { name: 'Allemagne', iso: 'DE', dial: '+49' }, { name: 'France', iso: 'FR', dial: '+33' }, { name: 'Côte d’Ivoire', iso: 'CI', dial: '+225' }, { name: 'Cameroun', iso: 'CM', dial: '+237' }, { name: 'RDC', iso: 'CD', dial: '+243' }, { name: 'Sénégal', iso: 'SN', dial: '+221' }, { name: 'Belgique', iso: 'BE', dial: '+32' }, { name: 'Suisse', iso: 'CH', dial: '+41' }, { name: 'Canada', iso: 'CA', dial: '+1' }, { name: 'États-Unis', iso: 'US', dial: '+1' }
]
export const emptyPreview: EventItem = { id: 0, title: 'Votre futur événement', description: 'Prévisualisation en direct.', category: 'business', city: '', country: '', venueName: '', organizerName: '', startsAt: new Date(Date.now()+86400000).toISOString(), endsAt: new Date(Date.now()+90000000).toISOString(), capacity: 100, brandColor: '#ff7a1a', tickets: [{ id: 0, name: 'Standard', kind: 'PAID', price: 0, currency: 'EUR', quantity: 100, sold: 0 }] }
export const platformModules: PlatformModule[] = [
  { key: 'box-office-link', area: 'organizer', title: 'Lien mobile organisateur / box-office', shortTitle: 'Box-office mobile', method: 'POST', endpoint: '/organizer/events/:eventId/box-office-link', description: 'Génère un lien sécurisé pour scanner, vendre et consulter la jauge depuis mobile.', fields: [{ name: 'deviceName', label: 'Nom appareil', placeholder: 'iPad entrée principale' }, { name: 'expiresInHours', label: 'Expire dans (heures)', type: 'number', placeholder: '24' }] },
  { key: 'door-sales', area: 'organizer', title: 'Vente à l’entrée', shortTitle: 'Door sales', method: 'POST', endpoint: '/organizer/events/:eventId/door-sales', description: 'Encaissement sur place avec attribution immédiate de billet et QR code.', fields: [{ name: 'buyerName', label: 'Nom acheteur', required: true }, { name: 'buyerEmail', label: 'Email acheteur', type: 'email' }, { name: 'buyerPhone', label: 'Téléphone' }, { name: 'ticketTypeId', label: 'ID option billet', type: 'number', required: true }, { name: 'quantity', label: 'Quantité', type: 'number', placeholder: '1' }, { name: 'paymentMethod', label: 'Paiement', options: ['CASH', 'CARD', 'MOBILE_MONEY'] }] },
  { key: 'seating', area: 'organizer', title: 'Plan de salle / seating', shortTitle: 'Seating', method: 'POST', endpoint: '/seat-maps', description: 'Crée un plan de salle. Les sièges peuvent ensuite être ajoutés via /api/seat-maps/seats.', fields: [{ name: 'name', label: 'Nom du plan', placeholder: 'Salle principale' }, { name: 'venueName', label: 'Lieu / salle', placeholder: 'Auditorium A' }, { name: 'layoutJson', label: 'Layout JSON', placeholder: '{"sections":["VIP","Standard"]}' }, { name: 'active', label: 'Actif', options: ['true', 'false'] }] },
  { key: 'promo-codes', area: 'organizer', title: 'Promos et codes d’accès', shortTitle: 'Promos', method: 'POST', endpoint: '/promo-codes', description: 'Codes de réduction, codes privés et quotas par campagne.', fields: [{ name: 'code', label: 'Code', placeholder: 'EARLYBIRD', required: true }, { name: 'type', label: 'Type', options: ['PROMO', 'ACCESS'] }, { name: 'discountPercent', label: 'Remise %', type: 'number' }, { name: 'maxRedemptions', label: 'Limite utilisations', type: 'number' }, { name: 'active', label: 'Actif', options: ['true', 'false'] }] },
  { key: 'waitlist', area: 'organizer', title: 'Liste d’attente', shortTitle: 'Waitlist', method: 'POST', endpoint: '/waitlist', description: 'Ajoute une personne en liste d’attente quand une option est complète.', fields: [{ name: 'fullName', label: 'Nom complet', required: true }, { name: 'email', label: 'Email', type: 'email' }, { name: 'phone', label: 'Téléphone' }, { name: 'ticketTypeId', label: 'ID option billet', type: 'number' }, { name: 'quantity', label: 'Quantité', type: 'number', placeholder: '1' }] },
  { key: 'refunds', area: 'organizer', title: 'Remboursements', shortTitle: 'Refunds', method: 'POST', endpoint: '/refunds', description: 'Crée une demande de remboursement total/partiel avec motif traçable.', fields: [{ name: 'reservationId', label: 'ID réservation', type: 'number', required: true }, { name: 'buyerEmail', label: 'Email acheteur', type: 'email' }, { name: 'amount', label: 'Montant', type: 'number' }, { name: 'reason', label: 'Motif', placeholder: 'Demande client' }] },
  { key: 'team-roles', area: 'organizer', title: 'Équipe et rôles', shortTitle: 'Team roles', method: 'POST', endpoint: '/team-members', description: 'Invite staff, scan-only, finance ou co-organisateur sur un événement.', fields: [{ name: 'email', label: 'Email invité', type: 'email', required: true }, { name: 'fullName', label: 'Nom invité' }, { name: 'role', label: 'Rôle', options: ['OWNER', 'MANAGER', 'BOX_OFFICE', 'SCANNER', 'FINANCE'] }, { name: 'permissions', label: 'Permissions', placeholder: 'scan,sell,refund' }] },
  { key: 'custom-forms', area: 'organizer', title: 'Formulaires personnalisés', shortTitle: 'Custom forms', method: 'POST', endpoint: '/attendee-questions', description: 'Questions additionnelles à poser à l’achat ou par détenteur de billet.', fields: [{ name: 'label', label: 'Question', placeholder: 'Entreprise / allergies / taille T-shirt', required: true }, { name: 'type', label: 'Type', options: ['TEXT', 'SELECT', 'CHECKBOX', 'DATE'] }, { name: 'required', label: 'Obligatoire', options: ['true', 'false'] }, { name: 'options', label: 'Options', placeholder: 'S,M,L,XL' }, { name: 'sortOrder', label: 'Ordre', type: 'number' }] },
  { key: 'marketing-tracking', area: 'organizer', title: 'Campagnes marketing et tracking', shortTitle: 'Marketing', method: 'POST', endpoint: '/marketing-campaigns', description: 'Campagnes, liens UTM et attribution des ventes par canal.', fields: [{ name: 'name', label: 'Nom campagne', placeholder: 'Instagram lancement', required: true }, { name: 'channel', label: 'Canal', options: ['EMAIL', 'WHATSAPP', 'LINKEDIN', 'INSTAGRAM', 'ADS'] }, { name: 'budget', label: 'Budget', type: 'number' }, { name: 'status', label: 'Statut', options: ['DRAFT', 'ACTIVE', 'PAUSED', 'DONE'] }] },
  { key: 'webhooks-developer', area: 'developer', title: 'Webhooks et paramètres développeur', shortTitle: 'Webhooks', method: 'POST', endpoint: '/developer/webhooks', description: 'Configure les callbacks API pour ventes, check-ins, remboursements et waitlist.', fields: [{ name: 'targetUrl', label: 'URL callback', type: 'url', required: true }, { name: 'events', label: 'Événements', placeholder: 'ticket.paid,attendee.checked_in,refund.created' }, { name: 'active', label: 'Actif', options: ['true', 'false'] }] },
]

export async function api<T>(path: string, options?: RequestInit): Promise<T> { const headers = { 'Content-Type': 'application/json', ...(options?.headers ?? {}) }; const res = await fetch(`${API_URL}${path}`, { ...options, headers }); if (!res.ok) { const raw = await res.text(); let message = raw || `${res.status} ${res.statusText}`; try { const parsed = JSON.parse(raw); message = parsed.message || parsed.error || message } catch { /* keep raw text */ } throw new Error(message) } return res.json() }
export async function uploadMedia(file: File, folder = 'events'): Promise<string> { const fd = new FormData(); fd.append('file', file); fd.append('folder', folder); const res = await fetch(`${API_URL}/media/upload`, { method: 'POST', body: fd }); if (!res.ok) throw new Error(await res.text()); const data = await res.json(); return data.publicUrl }
export function go(path: string) { history.pushState(null, '', path); dispatchEvent(new PopStateEvent('popstate')); scrollTo({ top: 0, behavior: 'smooth' }) }
export function parseQuery(path: string) { return new URLSearchParams(path.split('?')[1] ?? '') }
export function date(v: string) { return new Intl.DateTimeFormat('fr-FR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(v)) }
export function money(ticket?: TicketType) { if (!ticket) return 'Prix à définir'; return ticket.price === 0 ? 'Gratuit' : `${ticket.price.toLocaleString('fr-FR')} ${ticket.currency}` }
export function eventCategories(e: EventItem) { const raw = e.categories || e.category || ''; return raw.split(',').map(c => c.trim()).filter(Boolean) }
export function hasCategory(e: EventItem, category: string) { if (!category) return true; return eventCategories(e).some(c => c.toLowerCase() === category.toLowerCase()) }
export function ticketPriceSummary(tickets?: TicketType[]) { const list = (tickets ?? []).filter(Boolean); if (!list.length) return 'Prix à définir'; if (list.length === 1) return money(list[0]); const paid = list.filter(t => t.price > 0); const free = list.some(t => t.price === 0); if (!paid.length) return 'Gratuit'; const min = paid.reduce((a, t) => t.price < a.price ? t : a, paid[0]); const max = paid.reduce((a, t) => t.price > a.price ? t : a, paid[0]); const range = min.price === max.price && min.currency === max.currency ? money(min) : `${money(min)} – ${money(max)}`; return free ? `Gratuit + ${range}` : range }
export function TicketPriceList({ tickets }: { tickets?: TicketType[] }) { const list = (tickets ?? []).filter(Boolean); if (!list.length) return <div className="priceBox"><strong>Prix à définir</strong><small>Les options de billet seront bientôt disponibles.</small></div>; return <div className="ticketPriceGrid">{list.map(t => { const rest = Math.max(0, t.quantity - t.sold); return <article className="priceBox ticketPriceCard" key={t.id}><strong>{money(t)}</strong><b>{t.name}</b>{t.description && <small>{t.description}</small>}<small>{rest > 0 ? `${rest} place(s) restante(s)` : 'Épuisé'}</small></article> })}</div> }
export function addressOnly(e: EventItem) { return [e.addressLine, e.postalCode, e.city, e.country].filter(Boolean).join(', ') }
export function eventPlace(e: EventItem) { if (e.online) return '🌐 En ligne · lien envoyé par QR Code + email/WhatsApp'; const room = e.roomName ? `${e.roomName} · ` : ''; const exact = addressOnly(e); return `📍 ${room}${e.venueName ? e.venueName + ' · ' : ''}${exact || `${e.city}, ${e.country}`}` }
export function mapEmbed(e: EventItem) { const q = e.latitude && e.longitude ? `${e.latitude},${e.longitude}` : addressOnly(e); return `https://www.openstreetmap.org/export/embed.html?layer=mapnik&marker=${encodeURIComponent(q)}` }
export function phone(fd: FormData, base: string) { const dial = String(fd.get(`${base}Dial`) || ''); const raw = String(fd.get(base) || '').trim().replace(/^0+/, ''); return raw ? `${dial}${raw}` : '' }
export function eventOptions(events: EventItem[]) { return <datalist id="eventTitles">{events.map(e => <option value={e.title} key={e.id}>{e.city}, {e.country}</option>)}</datalist> }


export function Header({ account, setAccount }: { account: Account | null; setAccount: (a: Account | null) => void }) { return <nav className="nav"><button className="brand" onClick={() => go('/')}><span>✦</span>LightEvents</button><div className="links"><button onClick={() => go('/events')}>Événements</button>{account?.role === 'ORGANIZER' && <button onClick={() => go('/create')}>Publier</button>}<button onClick={() => go('/organizer')}>Organisateur</button><button onClick={() => go('/tickets')}>Mes tickets</button><button onClick={() => go('/help')}>ChatBot</button>{account?.role === 'ADMIN' && <button onClick={() => go('/admin')}>Admin</button>}</div><div className="authBox">{account ? <><small>{account.fullName} · {account.verified ? '✅' : '⚠️'}</small><button className="iconButton" title="Déconnexion" aria-label="Déconnexion" onClick={() => setAccount(null)}>🚪</button></> : <button className="iconButton" title="Connexion" aria-label="Connexion" onClick={() => go('/auth')}>🔐</button>}</div></nav> }
export function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="sectionTitle page"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><p>{text}</p></section> }
export function EventGrid({ events }: { events: EventItem[] }) { if (!events.length) return <section className="panel page emptyState">Aucun événement pour le moment.</section>; return <section className="eventGrid page">{events.map(e => <article className="eventCard" key={e.id} style={{ '--accent': e.brandColor || '#7c3aed' } as CSSProperties}><img src={e.coverImageUrl || e.generatedImageUrl || '/favicon.svg'} /><div className="eventBody"><span>{eventCategories(e).join(' · ') || e.category}</span><h3>{e.title}</h3><small className="organizerMini">Par {e.organizerName || 'Organisateur LightEvents'}</small><p>{e.description}</p><small>{eventPlace(e)} · 🗓️ {date(e.startsAt)}</small><div><strong>{ticketPriceSummary(e.tickets)}</strong><button onClick={() => go(`/events/${e.id}`)}>Détails</button></div></div></article>)}</section> }
export function PhoneField({ base, label }: { base: string; label: string }) { return <div className="two"><select name={`${base}Dial`} defaultValue="+49">{countries.map(c => <option key={c.iso} value={c.dial}>{c.name} {c.dial}</option>)}</select><input name={base} placeholder={label} /></div> }
export function CountrySelect({ name }: { name: string }) { return <select name={name} defaultValue="DE">{countries.map(c => <option key={c.iso} value={c.iso}>{c.name}</option>)}</select> }
export function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modalBackdrop"><section className="modal panel"><button className="close" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div> }
export function PageHero({ title, text }: { title: string; text: string }) { return <section className="pageHero page"><span className="eyebrow">LightEvents</span><h1>{title}</h1><p>{text}</p></section> }


export function AppFooter(){ const payments=['ORANGE_MONEY','MTN_MONEY','WAVE','AIRTEL_MONEY','MOOV_MONEY','STRIPE','PAYPAL']; return <footer className="footer richFooter"><div className="paymentLogos">{payments.map(p=><span key={p}>{p.replace('_',' ')}</span>)}</div><div className="footerLinks"><button onClick={()=>go('/policy/privacy')}>Privacy Policy</button><button onClick={()=>go('/policy/terms')}>Terms</button><button onClick={()=>go('/policy/refund')}>Refund Policy</button><button onClick={()=>go('/policy/cookies')}>Cookies</button><button onClick={()=>go('/help')}>Support</button></div><p>LightEvents · frais plateforme {platformFee}% · paiements internationaux et Mobile Money.</p></footer> }
export function ScrollTopButton(){ return <button className="scrollTop" onClick={()=>scrollTo({top:0,behavior:'smooth'})}>↑</button> }
